Core_Proje/Controllers/ExperiencesController.cs
using BusinessLayer.Concrete;
using DataAccesLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using BusinessLayer.ValidationRules;
using FluentValidation.Results;

namespace Core_Proje.Controllers
{
    public class ExperiencesController : Controller
    {
        ExperienceManager experienceManager = new ExperienceManager(new EfExperienceDAL());
        public IActionResult Index()
        {
            ViewBag.v1 = "Listeleme";
            ViewBag.v2 = "Deneyim";
            ViewBag.v3 = "Deneyim Listesi";
            ViewBag.DeneyimAct = "active";

            var experienceList = experienceManager.T_GetList();
            return View(experienceList);
         
        }
        [HttpGet]
        public IActionResult AddExperience()
        {
            ViewBag.v1 = "Ekleme";
            ViewBag.v2 = "Deneyim";
            ViewBag.v3 = "Deneyim Ekleme";

            return View();
        }
        [HttpPost]
        public IActionResult AddExperience(Experience experience)
        {
            ExperiencesValidator validations = new ExperiencesValidator();
            ValidationResult result = validations.Validate((experience));

            if (result.IsValid)
            {
                experienceManager.T_Add(experience);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();

       
        }
        public IActionResult DeleteExperience(int ID)
        {
            var values = experienceManager.T_GetByID(ID);
            experienceManager.T_Delete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditExperience(int ID)
        {
            ViewBag.v1 = "Düzenleme";
            ViewBag.v2 = "Deneyim";
            ViewBag.v3 = "Deneyim Güncelleme";

            var values = experienceManager.T_GetByID(ID);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditExperience(Experience experience)
        {
            ExperiencesValidator validations = new ExperiencesValidator();
            ValidationResult result = validations.Validate((experience));

            if (result.IsValid)
            {
                experienceManager.T_Update(experience);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
       
        }
    }
}

Core_Proje/Views/Experiences/AddExperience.cshtml
@model EntityLayer.Concrete.Experience
@{
    ViewData["Title"] = "AddExperience";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("AddExperience", "Experiences", FormMethod.Post))
{
    @Html.HiddenFor(x =>x.ExperienceID)
    <br />
    @Html.Label("Şirket Adı")
    @Html.TextBoxFor(x => x.Name, new {@class="form-control"})
    @Html.ValidationMessageFor(x => x.Name)
    <br />
    @Html.Label("Pozisyon")
    @Html.TextBoxFor(x => x.Mission, new {@class="form-control"})
    <br />
    <div class="row">
        <div class="col-md-6">
            @Html.Label("İşe Başlama Tarihi")
            @Html.TextBoxFor(x => x.BeginningDate, "{0:yyyy-MM-dd}", new { @class="form-control",type = "date" })
        </div>

        <div class="col-md-6">
            @Html.Label("İşten Çıkış Tarihi")
            @Html.TextBoxFor(x => x.EndDate, "{0:yyyy-MM-dd}", new { @class="form-control",type = "date" })
        </div>
    </div>
    <br />
    @Html.Label("Bilgiler")
    @Html.TextAreaFor(x => x.Description,10,3 ,new {@class="form-control"})
    <br />
    <button  class="btn btn-info">Kaydet</button>
}

Core_Proje/Views/Experiences/EditExperience.cshtml
@model EntityLayer.Concrete.Experience
@{
    ViewData["Title"] = "EditExperience";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("EditExperience", "Experiences", FormMethod.Post))
{
    @Html.HiddenFor(x =>x.ExperienceID)
    <br />
    @Html.Label("Şirket Adı")
    @Html.TextBoxFor(x => x.Name, new {@class="form-control"})
    @Html.ValidationMessageFor(x => x.Name)
    <br />
    @Html.Label("Pozisyon")
    @Html.TextBoxFor(x => x.Mission, new {@class="form-control"})
    <br />
    <div class="row">
        <div class="col-md-6">
            @Html.Label("İşe Başlama Tarihi")
            @Html.TextBoxFor(x => x.BeginningDate, "{0:yyyy-MM-dd}", new { @class="form-control",type = "date" })
        </div>

        <div class="col-md-6">
            @Html.Label("İşten Çıkış Tarihi")
            @Html.TextBoxFor(x => x.EndDate, "{0:yyyy-MM-dd}", new { @class="form-control",type = "date" })
        </div>
    </div>
    <br />
    @Html.Label("Bilgiler")
    @Html.TextAreaFor(x => x.Description,10,3 ,new {@class="form-control"})
    <br />
    <button class="btn btn-success">Güncelle</button>
}

Core_Proje/Views/Experiences/Index.cshtml
@using EntityLayer.Concrete;
@model List<Experience>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="card mb-4">
            <div class="card-header pb-0">

                <a href="#" class="btn btn-success" aria-haspopup="true" aria-expanded="false" style="float:right">
                    Yeni Kayıt &nbsp <i class="fa fa-refresh"></i>
                </a>



            </div>
            <div class="card-body px-0 pt-0 pb-2">
                <div class="table-responsive p-0">
                    <table class="table align-items-center justify-content-center mb-0">
                        <thead>
                            <tr>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Id</th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Şirket Adı & Pozisyonu </th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Görevleri</th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder text-center opacity-7 ps-2">Sil</th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder text-center opacity-7 ps-2">Güncelle</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td class="align-middle text-center">
                                        <div class="d-flex px-2">
                                            <div class="my-auto">
                                                <h6 class="mb-0 text-sm">@item.ExperienceID</h6>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="align-middle text-center">
                                        <div class="d-flex px-2 align-items-center " style="margin-left:-50px">
                                            <div>
                                                <h6 class="mb-0 text-sm">@item.Name</h6> - <span class="me-0 text-xs font-weight-bold">@item.Mission %</span>
                                            </div>
                                            <div class="my-auto">
                                                <h6 class="mb-0 text-sm">@item.BeginningDate.ToString("dd-MM-yyyy") - @item.EndDate.ToString("dd-MM-yyyy")g</h6>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="align-middle text-center">
                                        <div class="d-flex align-items-center justify-content-center" style="margin-left:-70px">
                                            <h6 class="mb-0 text-sm">@item.Description</h6>
                                        </div>
                                    </td>
                                    <td class="align-middle text-center">

                                        <a href="#" class="btn btn-danger " aria-haspopup="true" aria-expanded="false">
                                            Sil &nbsp <i class="fa fa-remove"></i>
                                        </a>
                                    </td>
                                    <td class="align-middle text-center">

                                        <a href="#" class="btn btn-primary " aria-haspopup="true" aria-expanded="false">
                                            Güncelle &nbsp <i class="fa fa-refresh"></i>
                                        </a>
                                    </td>
                                </tr>
                            }


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>