Core_Proje/Controllers/FeatureController.cs
using BusinessLayer.Abstract;
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccesLayer.Concrete;
using DataAccesLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace Core_Proje.Controllers
{
    public class FeatureController : Controller
    {
        FeatureManager featureManager = new FeatureManager(new EfFeatureDAL());
        public IActionResult Index()
        {
            ViewBag.v1 = "Listeleme";
            ViewBag.v2 = "Özellik";
            ViewBag.v3 = "Özellik Listesi";
            ViewBag.FeatureAct = "active";

            var values = featureManager.T_GetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddFeature()
        {
            ViewBag.v1 = "Ekleme";
            ViewBag.v2 = "Özellik";
            ViewBag.v3 = "Özellik Ekleme";

            return View();
        }
        [HttpPost]
        public IActionResult AddFeature(Feature feature)
        {
            FeatureValidator validations = new FeatureValidator();
            ValidationResult result = validations.Validate((feature));

            if (result.IsValid)
            {
               
                var cont = new Context();
                var parameterReturn = new SqlParameter
                {
                    ParameterName = "ReturnValue",
                    SqlDbType = System.Data.SqlDbType.Int,
                    Direction = System.Data.ParameterDirection.Output,
                };
                var resultSp = cont.Database.ExecuteSqlRaw("EXEC @returnValue = [dbo].[FeatureAddingBeforeUpdateStatus]", parameterReturn);
                int returnValue = (int)parameterReturn.Value; // 1 ise kayıt vardı pasif edildi, 0 ise kayıt yok baralı ekleme yapılabilir.

                featureManager.T_Add(feature);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();


        }
        public IActionResult DeleteFeature(int ID)
        {
            var values = featureManager.T_GetByID(ID);
            featureManager.T_Delete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditFeature(int ID)
        {
            ViewBag.v1 = "Düzenleme";
            ViewBag.v2 = "Özellik";
            ViewBag.v3 = "Özellik Güncelleme";

            var values = featureManager.T_GetByID(ID);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditFeature(Feature feature)
        {
            FeatureValidator validations = new FeatureValidator();
            ValidationResult result = validations.Validate((feature));

            if (result.IsValid)
            {
                var cont = new Context();
                var parameterReturn = new SqlParameter
                {
                    ParameterName = "ReturnValue",
                    SqlDbType = System.Data.SqlDbType.Int,
                    Direction = System.Data.ParameterDirection.Output,
                };
                var resultSp = cont.Database.ExecuteSqlRaw("EXEC @returnValue = [dbo].[FeatureAddingBeforeUpdateStatus]", parameterReturn);
                int returnValue = (int)parameterReturn.Value; // 1 ise kayıt vardı pasif edildi, 0 ise kayıt yok baralı güncelleme yapılabilir.



                featureManager.T_Update(feature);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();

        }
    }
}

Core_Proje/Views/Feature/AddFeature.cshtml
@model EntityLayer.Concrete.Feature
@{
    ViewData["Title"] = "AddFeature";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("AddFeature", "Feature", FormMethod.Post))
{
    @Html.HiddenFor(x =>x.FeatureID)
    <br />
    @Html.Label("Başlık")
    @Html.TextBoxFor(x => x.Header, new {@class="form-control"})
    @Html.ValidationMessageFor(x => x.Header)
    <br />
    @Html.Label("Ad Alanı")
    @Html.TextBoxFor(x => x.Name, new {@class="form-control"})
    @Html.ValidationMessageFor(x => x.Name)
    <br />
    @Html.Label("Bilgiler")
    @Html.TextAreaFor(x => x.Tiitle,10,3 ,new {@class="form-control"})
    @Html.ValidationMessageFor(x => x.Tiitle)
    <br />
    @Html.Label("Durumu")
    @Html.CheckBoxFor(m => m.Status)
    <br>
    <button class="btn btn-info">Kaydet</button>
}

Core_Proje/Views/Feature/EditFeature.cshtml
@model EntityLayer.Concrete.Feature
@{
    ViewData["Title"] = "EditFeature";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



@using (Html.BeginForm("EditFeature", "Feature", FormMethod.Post))
{
    @Html.HiddenFor(x =>x.FeatureID)
    <br />
    @Html.Label("Başlık")
    @Html.TextBoxFor(x => x.Header, new {@class="form-control"})
    @Html.ValidationMessageFor(x => x.Name)
    <br />
    @Html.Label("Başlık Alanı")
    @Html.TextBoxFor(x => x.Name, new {@class="form-control"})
    <br />
    @Html.Label("Bilgiler")
    @Html.TextAreaFor(x => x.Tiitle,10,3 ,new {@class="form-control"})
    <br />
    @Html.Label("Durumu")
    @Html.CheckBoxFor(m => m.Status)
    <br />
    <button class="btn btn-success">Güncelle</button>
}

Core_Proje/Views/Feature/Index.cshtml
@using EntityLayer.Concrete;
@model List<Feature>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="card mb-4">
            <div class="card-header pb-0">

                <a href="/Feature/AddFeature/" class="btn btn-success" aria-haspopup="true" aria-expanded="false" style="float:right">
                    Yeni Kayıt &nbsp <i class="fa fa-refresh"></i>
                </a>



            </div>
            <div class="card-body px-0 pt-0 pb-2">
                <div class="table-responsive p-0">
                    <table class="table align-items-center justify-content-center mb-0" style="width: 100%;">
                        <thead>
                            <tr>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Id</th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Başlık</th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Ad</th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Özet Bilgi</th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Durum</th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder text-center opacity-7 ps-2">Sil</th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder text-center opacity-7 ps-2">Güncelle</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td class="align-middle text-center">
                                        <div class="d-flex px-3">
                                            <div class="my-auto">
                                                <h6 class="mb-0 text-sm">@item.FeatureID</h6>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="align-middle text-center">
                                        <div class="d-flex px-5 align-items-center " style="margin-left:-50px">
                                            <div>
                                                <h6 class="mb-0 text-sm">@item.Header</h6> 
                                            </div>
                                        </div>
                                    </td>
                                    <td class="align-middle text-left">
                                        <div class="d-flex px-5 align-items-center " style="margin-left:-50px">
                                            <div>
                                                <h6 class="mb-0 text-sm">@item.Name</h6> 
                                            </div>
                                        </div>
                                    </td>
                                    <td class="align-middle text-left">
                                        <div class="d-flex px-5 align-items-center " style="margin-left:-50px">
                                            <div>
                                                <h6 class="mb-0 text-sm">@item.Tiitle</h6>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="align-middle text-left">
                                        <div class="d-flex px-5 align-items-center " style="margin-left:-50px">
                                            <div>
                                                @if (item.Status == false)
                                                {
                                                    <h6 class="mb-0 text-sm" style="color:darkred">Pasif</h6>
                                                }
                                                else
                                                {
                                                    <h6 class="mb-0 text-sm" style="color:darkgreen">Aktif</h6>
                                                }
                                             
                                            </div>
                                        </div>
                                    </td>
                                    <td class="align-middle text-center">

                                        <a href="/Feature/DeleteFeature/@item.FeatureID" class="btn btn-danger " aria-haspopup="true" aria-expanded="false">
                                            Sil &nbsp <i class="fa fa-remove"></i>
                                        </a>
                                    </td>
                                    <td class="align-middle text-center">

                                        <a href="/Feature/EditFeature/@item.FeatureID" class="btn btn-primary " aria-haspopup="true" aria-expanded="false">
                                            Güncelle &nbsp <i class="fa fa-refresh"></i>
                                        </a>
                                    </td>
                                </tr>
                            }


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>